### ISSUE TITLE
delete branches after merging

### ISSUE THREAD

**Issue by ktdreyer** [RoryWirch/brew-channel-validation#4]
There's still an old `testing` branch [in this repo](https://github.com/RoryWirch/brew-channel-validation/branches), even after merging #1 

Go to the [Settings tab](https://github.com/RoryWirch/brew-channel-validation/settings) for this repo

Click the "Automatically delete head branches" setting

This will keep you from having a million branches :)

**Comment by RoryWirch** [comment]
That's cool, I just changed it so it should automatically delete branches now
