### ISSUE TITLE
delete connection.py and tests/test_connection.py

### ISSUE THREAD

**Issue by ktdreyer** [RoryWirch/brew-channel-validation#41]
since we're not using these any more

**Comment by ktdreyer** [comment]
Would you mind assigning this to @jennkimerson ?

**Comment by RoryWirch** [comment]
@ktdreyer Just reassigned this issue to @jennkimerson

**Comment by RoryWirch** [comment]
This issue should also involve removing psycopg2 from the requirements.txt file
